### ISSUE TITLE
Additional elements not recognized when containing an attribute

### ISSUE THREAD

**Issue by mgazanayi** [vidal-community/atom-jaxb#20]
When we unmarshall an WML feed containing this kind of elements `<vidal:textJustificationFlag  name="ORANGE">Codage à vérifier</vidal:textJustificationFlag>`, we don't find this value on the additionalElements collection. This is due to the `attribute name="ORANGE"` part. When simply removing it, the element is recognized.

**Comment by mgazanayi** [comment]
When debugging, I watched that the problem is linked to the absence of a namespaceURI for the item.

**Comment by fbiville** [comment]
Which version?

**Comment by mgazanayi** [comment]
@fbiville : 0.3-SNAPSHOT (master)

**Comment by mgazanayi** [comment]
Here is a stacktrace:
`javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 52; Le préfixe "vidal" de l'élément "vidal:textJustificationFlag" n'est pas lié.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:522)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:223)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:189)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at fr.vidal.oss.jaxb.atom.UnmarshallingTest.unmarshall_feed_with_vendor_specific_element(UnmarshallingTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

**Comment by Kevcoq** [comment]
Hi,

I have the same problem.
I temporarily fix the bug with :
 	
`
result.addAttribute(Attribute.builder(item.getLocalName(), item.getTextContent()).withNamespace(
namespace(item.getNamespaceURI() != null ? item : element)).build());`

in SimpleElementAdapter:unmarshal .

The namespace is not null and the element become valid.

**Comment by mgazanayi** [comment]
@Kevcoq : I tried this solution yesterday and it resolves the problem.
Tests keeps failing because when you don't specify a namespace for an entry, you have to specify it for each item. PR is coming.

**Comment by fhiegel** [comment]
Hello.
From [here](http://www.xmlplease.com/xml/attributexmlns/) :
> An attribute never inherits the namespace of its parent element.

We correct this issue in #26

**Comment by jcgay** [comment]
Fixed in 3aeddae652f541e5b11bad14cd298945fbd2cd4e
